### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by lachlangreenbank** [jlgaffney/Neo.SmartContract.Poll#1]
Hello,

Its cool to see your repo of a neo smart contract, I'm interested in how to deploy and how to interact with it. would you be able to provide any of this info?

GO NEO!

**Comment by justingaffney** [comment]
Hey,

This code is just one of my initial attempts to try and learn how to write NEO smart contracts, and this particular smart contract is full of flaws so please don't use it as an example. Unfortunately due to work commitments I haven't and won't be able to work on any NEO related development for a while.

If you want some other smart contract examples, take a look at this repo https://github.com/neo-project/examples.

I'd recommend looking here https://github.com/neo-project/docs/tree/master/en-us/sc. It's the repo for NEO's current smart contract documentation. It is still lacking a bit, and there aren't any clear tutorials yet, but I'd start reading through that if I were you.

Also if you have any specific questions that the documentation can't answer, try going to the #develop channel of NEO's Slack. Here's the shared invite link if you haven't already joined it https://neosmarteconomy.slack.com/join/shared_invite/MjI5MTc0NTIwMDM2LTE1MDMyNDY3MDctYzQ2MzM4ZjU3ZA. NEO community developers are regularly communicating in that channel, and they should be able to help answer any technical questions about deploying contracts and interacting with other contracts that you may have, as many of them have been dealing with the same issues over the last couple of months.

Sorry I couldn't be of much assistance myself, but right now I am unable to find enough spare time outside of my working hours to do any NEO related development.

GO NEO!

**Comment by lachlangreenbank** [comment]
ok thanks for the info mate!

Im in the same boat as work commitments are stopping me really digging into
neo, its a promising project. If you later start doing more work and want
others involved feel free to send me an invite :)

Cheers,

Lachlan
